# Generated by Django 5.0.7 on 2026-08-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_user_id_df2351_idx',
            old_name='accounts_act_user_id_8b2c4b_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_action_0ce76e_idx',
            old_name='accounts_act_action_1bb3d4_idx',
        ),
    ]
