# Generated by Django 5.2.17 on 2026-08-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog_admin_ai_provider'),
        ('accounts', '0002_rename_accounts_act_user_id_8b2c4b_idx_accounts_ac_user_id_df2351_idx_and_more'),
    ]

    operations = [
    ]
