# Generated by Django 5.2.17 on 2026-08-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260820_1558'),
        ('accounts', '0003_userbudget'),
    ]

    operations = [
    ]
