# Generated by Django 5.2.17 on 2026-08-25 05:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0003_merge_20260820_1558_0003_userbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbudget',
            name='cost_limit_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
