# Generated by Django 5.2.17 on 2026-08-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='blog', max_length=80)),
                ('topic', models.CharField(max_length=500)),
                ('tone', models.CharField(default='professional', max_length=100)),
                ('word_count', models.PositiveIntegerField(default=800)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='sites_app.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
