# Generated by Django 5.2.17 on 2026-08-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_aiusageevent_chatsession_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='assistant_a_feature_48bc8c_idx',
            old_name='assistant_a_feature_8f2f77_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='assistant_a_session_b57d65_idx',
            old_name='assistant_a_session__a6e7d4_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='assistant_a_provide_0ccff7_idx',
            old_name='assistant_a_provide_6b2f2a_idx',
        ),
    ]
