# Generated by Django 5.2.17 on 2026-08-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=80, unique=True)),
                ('brand_voice', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='English', max_length=80)),
                ('content_rules', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_output_tokens', models.PositiveIntegerField(default=4096)),
                ('system_prompt', models.TextField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='sites_app.site')),
            ],
        ),
    ]
