# Generated by Django 5.2.17 on 2026-08-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='model',
            field=models.CharField(default='gemini-3.6-flash', max_length=100),
        ),
    ]
