export const CONTENT_CATALOG = [
  { id: 'letter', label: 'Letters', purpose: 'Create formal, business and personal letters for a wide range of situations.', formats: [
    ['letter_cover', 'Cover letter'], 
    ['letter_business', 'Business letter'], 
    ['letter_formal', 'Formal letter'], 
    ['letter_resignation', 'Resignation letter'], 
    ['letter_recommendation', 'Recommendation letter'], 
    ['letter_reference', 'Reference letter'], 
    ['letter_appointment', 'Appointment letter'], 
    ['letter_offer', 'Offer letter'], 
    ['letter_complaint', 'Complaint letter'], 
    ['letter_apology', 'Apology letter'], 
    ['letter_inquiry', 'Inquiry letter'], 
    ['letter_invitation', 'Invitation letter'], 
    ['letter_thank_you', 'Thank-you letter'], 
    ['letter_intent', 'Letter of intent'], 
    ['letter_authorization', 'Authorization letter'], 
    ['letter_permission', 'Permission letter'], 
    ['letter_termination', 'Termination letter'], 
    ['letter_warning', 'Warning letter'], 
    ['letter_congratulations', 'Congratulations letter'], 
    ['letter_condolence', 'Condolence letter'], 
    ['letter_personal', 'Personal letter'], 
  ] },
  { id: 'website', label: 'Website Content', purpose: 'Explain your business, services, products and customer journey.', formats: [
    ['website_home', 'Home page content'], 
    ['website_about', 'About Us'], 
    ['website_services', 'Services page'], 
    ['website_product', 'Product page'], 
    ['website_category', 'Category page'], 
    ['website_industry', 'Industry / solution page'], 
    ['website_location', 'Location page'], 
    ['website_landing', 'Landing page'], 
    ['website_case_study', 'Case study page'], 
    ['website_portfolio', 'Portfolio / project page'], 
    ['website_testimonial', 'Testimonials'], 
    ['website_faq', 'FAQ page'], 
    ['website_contact', 'Contact page'], 
    ['website_careers', 'Careers / jobs page'], 
    ['website_company_profile', 'Company profile'], 
    ['website_terms', 'Terms & Conditions'], 
    ['website_privacy', 'Privacy Policy'], 
    ['website_refund', 'Refund / Cancellation Policy'], 
    ['website_shipping', 'Shipping / Delivery Policy'], 
    ['website_cookie', 'Cookie Policy'], 
  ] },
  { id: 'seo_blogs', label: 'SEO Blogs', purpose: 'Build organic traffic with useful, keyword-focused blog content.', formats: [
    ['seo_blog_post', 'SEO blog post'], 
  ] },
  { id: 'seo_articles', label: 'SEO Articles', purpose: 'Build rankings, topical authority and search visibility.', formats: [
    ['seo_long_form', 'Long-form article'], 
    ['seo_pillar', 'Pillar page'], 
    ['seo_topic_cluster', 'Topic cluster content'], 
    ['seo_how_to', 'How-to guide'], 
    ['seo_ultimate', 'Ultimate guide'], 
    ['seo_listicle', 'Listicle'], 
    ['seo_comparison', 'Comparison article'], 
    ['seo_best', 'Best X article'], 
    ['seo_vs', 'X vs Y article'], 
    ['seo_faq', 'FAQ content'], 
    ['seo_glossary', 'Glossary / definition page'], 
    ['seo_location', 'Location-based SEO page'], 
    ['seo_service', 'Service-specific SEO page'], 
    ['seo_product_comparison', 'Product comparison page'], 
    ['seo_programmatic', 'Programmatic SEO page'], 
    ['seo_featured_snippet', 'Featured-snippet content'], 
    ['seo_paa', 'People Also Ask content'], 
  ] },
  { id: 'guest_posts', label: 'Guest Posts', purpose: 'Create external content for backlinks, referral traffic and authority.', formats: [
    ['guest_post', 'Guest post'], 
    ['guest_article', 'Guest article'], 
    ['guest_sponsored', 'Sponsored article'], 
    ['guest_editorial', 'Editorial article'], 
    ['guest_contributor', 'Contributor article'], 
    ['guest_niche_edit', 'Niche edit'], 
    ['guest_link_insertion', 'Link insertion content'], 
    ['guest_resource', 'Resource-page submission'], 
    ['guest_directory', 'Directory description'], 
    ['guest_business_profile', 'Business profile description'], 
    ['guest_local_citation', 'Local citation'], 
    ['guest_forum', 'Forum post'], 
    ['guest_qa', 'Q&A answer'], 
    ['guest_comment', 'Blog comment'], 
    ['guest_web20', 'Web 2.0 article'], 
    ['guest_pdf', 'PDF submission'], 
    ['guest_infographic', 'Infographic submission'], 
    ['guest_image', 'Image submission'], 
    ['guest_bookmark', 'Bookmarking description'], 
  ] },
  { id: 'press_releases', label: 'Press Releases', purpose: 'Create news-oriented PR and media content for brand visibility.', formats: [
    ['pr_release', 'Press release'], 
    ['pr_news', 'News release'], 
    ['pr_company', 'Company announcement'], 
    ['pr_product_launch', 'Product launch announcement'], 
    ['pr_service_launch', 'Service launch announcement'], 
    ['pr_partnership', 'Partnership announcement'], 
    ['pr_award', 'Award announcement'], 
    ['pr_funding', 'Funding announcement'], 
    ['pr_expansion', 'Expansion announcement'], 
    ['pr_executive', 'Executive appointment'], 
    ['pr_event', 'Event announcement'], 
    ['pr_media_pitch', 'Media pitch'], 
    ['pr_journalist_pitch', 'Journalist pitch'], 
    ['pr_founder_interview', 'Founder interview'], 
    ['pr_expert_commentary', 'Expert commentary'], 
    ['pr_company_news', 'Company news article'], 
  ] },
  { id: 'landing_pages', label: 'Landing Pages', purpose: 'Create focused pages designed to convert visitors into enquiries or actions.', formats: [
    ['landing_page', 'Landing page'], 
  ] },
  { id: 'case_studies', label: 'Case Studies', purpose: 'Demonstrate real customer or project outcomes to build trust and conversions.', formats: [
    ['case_study', 'Case study'], 
    ['case_success_story', 'Success story'], 
  ] },
  { id: 'social', label: 'Social Media Posts', purpose: 'Create platform-native social content for engagement, education and promotion.', formats: [
    ['social_facebook_post', 'Facebook post'], 
    ['social_facebook_promo', 'Facebook promotional post'], 
    ['social_facebook_education', 'Facebook educational post'], 
    ['social_facebook_carousel', 'Facebook carousel'], 
    ['social_facebook_poll', 'Facebook poll'], 
    ['social_facebook_event', 'Facebook event post'], 
    ['social_facebook_reel', 'Facebook reel'], 
    ['social_instagram_post', 'Instagram post'], 
    ['social_instagram_reel', 'Instagram reel'], 
    ['social_instagram_story', 'Instagram story'], 
    ['social_instagram_carousel', 'Instagram carousel'], 
    ['social_instagram_caption', 'Instagram caption'], 
    ['social_instagram_promo', 'Instagram promotional creative'], 
    ['social_instagram_education', 'Instagram educational content'], 
    ['social_linkedin_company', 'LinkedIn company post'], 
    ['social_linkedin_founder', 'LinkedIn founder post'], 
    ['social_linkedin_thought', 'LinkedIn thought-leadership post'], 
    ['social_linkedin_insight', 'LinkedIn industry insight'], 
    ['social_linkedin_case', 'LinkedIn case study'], 
    ['social_linkedin_employee', 'LinkedIn employee story'], 
    ['social_linkedin_recruitment', 'LinkedIn recruitment post'], 
    ['social_linkedin_document', 'LinkedIn document / carousel'], 
    ['social_x_post', 'X / Twitter short post'], 
    ['social_x_thread', 'X / Twitter thread'], 
    ['social_x_news', 'X / Twitter news / commentary'], 
    ['social_x_opinion', 'X / Twitter industry opinion'], 
  ] },
  { id: 'video', label: 'Video Content', purpose: 'Create scripts and supporting copy for video reach and education.', formats: [
    ['video_title', 'Video title'], 
    ['video_description', 'Video description'], 
    ['video_script', 'Video script'], 
    ['video_shorts', 'Shorts script'], 
    ['video_tutorial', 'Tutorial'], 
    ['video_demo', 'Product demonstration'], 
    ['video_explainer', 'Explainer video'], 
    ['video_interview', 'Video interview'], 
  ] },
  { id: 'infographics', label: 'Infographics', purpose: 'Turn information into visual-first, shareable content concepts.', formats: [
    ['visual_infographic', 'Infographic'], 
    ['visual_chart', 'Chart'], 
    ['visual_diagram', 'Diagram'], 
    ['visual_statistics', 'Statistics graphic'], 
    ['visual_quote', 'Quote graphic'], 
    ['visual_social', 'Social media creative'], 
    ['visual_banner', 'Banner'], 
    ['visual_website_banner', 'Website banner'], 
    ['visual_product_image', 'Product image brief'], 
    ['visual_product_comparison', 'Product comparison graphic'], 
    ['visual_explainer_video', 'Explainer video concept'], 
    ['visual_motion', 'Motion graphic'], 
    ['visual_gif', 'Animated GIF concept'], 
    ['visual_presentation', 'Presentation'], 
    ['visual_slide_deck', 'Slide deck'], 
    ['visual_meme', 'Meme'], 
  ] },
  { id: 'email', label: 'Email Content', purpose: 'Create promotional, lifecycle, transactional and retention email copy.', formats: [
    ['email_promotional', 'Promotional email'], 
    ['email_newsletter', 'Newsletter'], 
    ['email_product_announcement', 'Product announcement email'], 
    ['email_service_announcement', 'Service announcement email'], 
    ['email_welcome', 'Welcome email'], 
    ['email_nurture', 'Lead nurturing email'], 
    ['email_follow_up', 'Follow-up email'], 
    ['email_abandoned_cart', 'Abandoned-cart email'], 
    ['email_offer', 'Offer email'], 
    ['email_event', 'Event invitation email'], 
    ['email_retention', 'Customer retention email'], 
    ['email_reengagement', 'Re-engagement email'], 
    ['email_transactional', 'Transactional email'], 
  ] },
  { id: 'whitepapers', label: 'White Papers / E-books', purpose: 'Create high-value B2B lead-generation and authority assets.', formats: [
    ['b2b_whitepaper', 'White paper'], 
    ['b2b_research_report', 'Research report'], 
    ['b2b_industry_report', 'Industry report'], 
    ['b2b_case_study', 'Case study'], 
    ['b2b_success_story', 'Success story'], 
    ['b2b_ebook', 'E-book'], 
    ['b2b_business_guide', 'Business guide'], 
    ['b2b_buyer_guide', 'Buyer guide'], 
    ['b2b_solution_brief', 'Solution brief'], 
    ['b2b_product_brochure', 'Product brochure'], 
    ['b2b_company_profile', 'Company profile'], 
    ['b2b_technical_doc', 'Technical documentation'], 
    ['b2b_application_note', 'Application note'], 
    ['b2b_trend_report', 'Industry trend report'], 
    ['b2b_market_analysis', 'Market analysis'], 
    ['b2b_roi_study', 'ROI study'], 
    ['b2b_customer_success', 'Customer success story'], 
  ] },
  { id: 'local_seo', label: 'Local SEO Content', purpose: 'Create city, area and local-business content for regional search visibility.', formats: [
    ['local_gbp_post', 'Google Business Profile post'], 
    ['local_landing', 'Local landing page'], 
    ['local_city_service', 'City service page'], 
    ['local_area', 'Area page'], 
    ['local_business_description', 'Local business description'], 
    ['local_service_article', 'Local service article'], 
    ['local_best_city', 'Best service in city content'], 
    ['local_near_me', 'Near me content'], 
    ['local_faq', 'Local FAQ'], 
    ['local_event', 'Local event content'], 
    ['local_directory', 'Local business directory profile'], 
    ['local_citation', 'Local citation'], 
  ] },
  { id: 'product', label: 'Product Content', purpose: 'Create e-commerce and marketplace copy that explains products and improves conversion.', formats: [
    ['product_description', 'Product description'], 
    ['product_short_description', 'Short product description'], 
    ['product_long_description', 'Long product description'], 
    ['product_specifications', 'Product specifications'], 
    ['product_benefits', 'Product benefits'], 
    ['product_category_description', 'Category description'], 
    ['product_brand_description', 'Brand description'], 
    ['product_buying_guide', 'Buying guide'], 
    ['product_comparison', 'Product comparison article'], 
    ['product_gift_guide', 'Gift guide'], 
    ['product_seasonal', 'Seasonal content'], 
    ['product_faq', 'Product FAQ'], 
    ['product_review', 'Product review'], 
    ['product_seller_description', 'Seller / vendor description'], 
    ['product_marketplace_profile', 'Marketplace seller profile'], 
  ] },
  { id: 'lead_generation', label: 'Lead Generation', purpose: 'Create assets and pages designed specifically to generate enquiries and conversions.', formats: [
    ['lead_landing', 'Lead-generation landing page'], 
    ['lead_magnet', 'Lead magnet'], 
    ['lead_free_guide', 'Free guide'], 
    ['lead_ebook', 'E-book'], 
    ['lead_checklist', 'Checklist'], 
    ['lead_template', 'Template'], 
    ['lead_calculator', 'Calculator concept'], 
    ['lead_quiz', 'Quiz'], 
    ['lead_free_audit', 'Free audit'], 
    ['lead_consultation', 'Free consultation'], 
    ['lead_demo', 'Demo request page'], 
    ['lead_quote', 'Quote request page'], 
    ['lead_download', 'Download page'], 
    ['lead_webinar', 'Webinar registration page'], 
  ] },
  { id: 'thought_leadership', label: 'Thought Leadership', purpose: 'Build brand authority through expertise, analysis and informed points of view.', formats: [
    ['thought_leadership_article', 'Thought-leadership article'], 
    ['thought_expert_commentary', 'Expert commentary'], 
    ['thought_founder', 'Founder perspective'], 
    ['thought_industry_opinion', 'Industry opinion'], 
    ['thought_analysis', 'Expert analysis'], 
  ] },
  { id: 'reputation', label: 'Reputation & Trust', purpose: 'Strengthen credibility with proof, profiles, recognition and trust content.', formats: [
    ['trust_testimonial', 'Customer testimonial'], 
    ['trust_review', 'Customer review'], 
    ['trust_case_study', 'Case study'], 
    ['trust_success_story', 'Success story'], 
    ['trust_award', 'Award'], 
    ['trust_certification', 'Certification'], 
    ['trust_client_logos', 'Client logos copy'], 
    ['trust_membership', 'Industry membership'], 
    ['trust_page', 'Trust page'], 
    ['trust_expert_profile', 'Expert profile'], 
    ['trust_founder_profile', 'Founder profile'], 
    ['trust_employee_profile', 'Employee profile'], 
    ['trust_media_mention', 'Media mention'], 
  ] },
  { id: 'technical', label: 'Technical / Product Docs', purpose: 'Create precise technical and product documentation for users, developers and B2B teams.', formats: [
    ['technical_manual', 'User manual'], 
    ['technical_installation', 'Installation guide'], 
    ['technical_api', 'API documentation'], 
    ['technical_guide', 'Technical guide'], 
    ['technical_knowledge_base', 'Knowledge-base article'], 
    ['technical_troubleshooting', 'Troubleshooting article'], 
    ['technical_product_doc', 'Product documentation'], 
    ['technical_developer_doc', 'Developer documentation'], 
    ['technical_faq', 'Technical FAQ'], 
    ['technical_release_notes', 'Release notes'], 
    ['technical_update', 'Product update announcement'], 
    ['technical_specs', 'Specifications'], 
    ['technical_datasheet', 'Datasheet'], 
  ] },
];

export const CONTENT_FORMATS = Object.fromEntries(CONTENT_CATALOG.flatMap(c => c.formats.map(([id,label]) => [id,{id,label,categoryId:c.id,categoryLabel:c.label,purpose:c.purpose}])));
export function getCategory(id){return CONTENT_CATALOG.find(x=>x.id===id)||CONTENT_CATALOG[0];}
export function getFormat(id){return CONTENT_FORMATS[id]||CONTENT_FORMATS[CONTENT_CATALOG[0].formats[0][0]];}